[package]
name = "carbon_macros"
version = "0.0.0"
edition = "2021"
author = "GorillaDevs Inc."

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.11"
quote = "1.0.26"
